### PR TITLE
window-list: Dragging files to window list and hovering activates window

### LINKED ISSUE #202: Dragging files between programs using the window list not working
This is a common feature available on other panels and on Windows.
TL;DR it seems that dragging a file from my file manager to another program, by holding the file over that other program's running icon on the window list, does not work.
Pinging @soreau for advice.

### PR DESCRIPTION
**Pull request by trigg**
Intended to fix #202

### CODE REVIEW

File: src/panel/widgets/window-list/toplevel.cpp [hunk 1]
```diff
@@ -40,6 +41,7 @@ class WayfireToplevel::impl
     Gtk::Menu menu;
     Gtk::MenuItem minimize, maximize, close;
     Glib::RefPtr<Gtk::GestureDrag> drag_gesture;
+    sigc::connection m_drag_timeout;
```
Comment (ammen99) [inline src/panel/widgets/window-list/toplevel.cpp:44]: Should we disconnect the connection in the object destructor as well? Or are we somehow guaranteed we'll get a drag leave first?

Comment (trigg) [reply src/panel/widgets/window-list/toplevel.cpp:44]: Most likely will but actually it's probably better to be safe.

**Review by ammen99 — APPROVED** [review]
Thanks!
