### PR TITLE
fix #138

### LINKED ISSUE #138: [wf-panel] Autohide (well, "autoshow") is broken on the latest wayfire version
Steps to reproduce:
 - autohide is enabled
 - launch `wf-panel`
   - panel appears and doesn't hide (btw it should)
 - move mouse cursor into the panel's area and then out
   - panel hides
 - move mouse cursor back into the screen edge
   - panel doesn't show but expected to show
   
-----
What I found out:
 - changing `-get_allocated_height()` to `0.001 - get_allocated_height()` [here](https://github.com/WayfireWM/wf-shell/blob/master/src/util/wf-autohide-window.cpp#L239) fixes this bug, but it's weird and makes panel not to hide entirely

### PR DESCRIPTION
**Pull request by NamorNiradnug**
Fixes #138

### CODE REVIEW

File: src/util/wf-autohide-window.cpp [hunk 1]
```diff
@@ -286,8 +286,9 @@ bool WayfireAutohidingWindow::update_margin()
     {
         gtk_layer_set_margin(this->gobj(),
             get_anchor_edge(position), y_position);
-
-        this->queue_draw(); // XXX: is this necessary?
+        if (get_window())
```
Comment (ammen99) [inline src/util/wf-autohide-window.cpp:289]: Does this work reliably? Previously you have said that this doesn't always work.

File: src/util/wf-autohide-window.cpp [hunk 2]
```diff
@@ -286,8 +286,9 @@ bool WayfireAutohidingWindow::update_margin()
...
+            wl_surface_commit(get_wl_surface());
```
Comment (ammen99) [inline src/util/wf-autohide-window.cpp:290]: It would also be a good idea to add a comment explaining why we do the commit here instead of queue_draw()

File: src/util/wf-autohide-window.cpp (hunk 1 above)
Comment (NamorNiradnug) [reply src/util/wf-autohide-window.cpp:289]: It works together with the second chance (which is animation start)

File: src/util/wf-autohide-window.cpp (hunk 2 above)
Comment (NamorNiradnug) [reply src/util/wf-autohide-window.cpp:290]: It's not instead btw, it doesn't work without `queue_draw`

**Comment by NamorNiradnug** [comment]
I think it works
I use wf-panel with the patch for 2 days

**Review by ammen99 — APPROVED** [review]
Thanks!
